FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential qemu-user

COPY . /shecc
WORKDIR /shecc
RUN make config ARCH=arm
RUN make

FROM ubuntu:20.04 as package
COPY --from=builder /shecc/out/shecc /
